apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mysql/Volume/PersistentVolume.yaml
  - ./mysql/Volume/PersistentVolumeClaim.yaml
  - ./mysql/mysql.yaml
  - ./mysql/mysql_LoadBalancer.yaml
  - ./mediawiki/Volume/PersistentVolume.yaml
  - ./mediawiki/Volume/PersistentVolumeClaim.yaml
  - ./mediawiki/Deployment.yaml
  - ./mediawiki/Mediawiki_LoadBalancer.yaml