apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
spec:
  selector:
    app: mysql
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: mysql-port
  type: LoadBalancer
  loadBalancerIP: 192.168.30.11