apiVersion: v1
kind: Service
metadata:
  name: velocity-lb
spec:
  selector:
    app: velocity
  ports:
  - name: velocity-port
    port: 25565
    protocol: TCP
    targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.35.1