kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard-lb
  name: kubernetes-dashboard-lb
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  type: LoadBalancer