apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/mediawiki
    type: DirectoryOrCreate