apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce