apiVersion: v1
kind: Service
metadata:
  name: velocity-debug-lb
spec:
  selector:
    app: velocity-debug
  ports:
  - name: velocity-debug-port
    port: 25565
    protocol: TCP
    targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.35.2