volumes:
  cloudflared-home:

services:
  tcp-cloudflared:
    image: ghcr.io/giganticminecraft/cloudflared-with-auto-dns-route:sha-6455b98
    volumes:
      - cloudflared-home:/root
      - ./cloudflared-tunnel-config.yml:/etc/cloudflared/tunnel-config.yml
    network_mode: "host"
    restart: always
    environment:
      TUNNEL_NAME: tcp-cloudflared-nanairo-Tunnel