version: '3.7'

services:
  velocity:
    image: ghcr.io/namagominetwork/namagomi-velocity:hoge
    ports:
      - "7000:7000"
    environment:
      - VELOCITY_URL=https://papermc.io/api/v2/projects/velocity/versions/3.1.1/builds/98/downloads/velocity-3.1.1-98.jar
      - VELOCITY_JARNAME=velocity-3.1.1-98.jar
      - MAX_MEM=2G
      - SERVER_ICON=https://raw.githubusercontent.com/NamagomiNetwork/icon/main/server-icon.png
    volumes:
      - ./velocity.toml:/server/velocity.toml
      - ./data/plugins:/server/plugins
      - ./data/logs:/server/logs