apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - env:
            - name: TUNNEL_NAME
              value: argocd-namagomi
            - name: CLOUDFLARED_HOSTNAME
              value: namagomi-argocd.nabr2730.com
            - name: CLOUDFLARED_SERVICE
              value: http://argocd-server.argocd
          image: minio/minio
          name: minio
          resources: 
            limits:
              memory: "700Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /root
              name: minio-pv
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pvc
status: {}