apiVersion: v1
kind: Service
metadata:
  name: minio-lb
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
  - name: port-9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: port-9001
    port: 9001
    protocol: TCP
    targetPort: 9001
  type: LoadBalancer
  loadBalancerIP: 192.168.35.20