apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/minecraft-server
    type: DirectoryOrCreate