apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mediawiki
    app: mediawiki  
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki  
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - image: ghcr.io/namagominetwork/mediawiki:2022.6.10-mediawiki1.38.1
          name: mediawiki
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: mediawiki-pv
      volumes:
        - name: mediawiki-pv
          persistentVolumeClaim:
            claimName: mediawiki-pvc
status: {}