apiVersion: v1
kind: Service
metadata:
  name: mediawiki-lb
spec:
  selector:
    app.kubernetes.io/name: mediawiki
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.30.111