apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-mod-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce