apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-mod-pv
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/minecraft-server
    type: DirectoryOrCreate