apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-lb
spec:
  selector:
    app: mc
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.30.155