apiVersion: v1
kind: Service
metadata:
  name: bungeecord-lb
spec:
  selector:
    app: bungeecord
  ports:
  - name: bungee-port
    port: 7000
    protocol: TCP
    targetPort: bungee-port
  type: LoadBalancer
  loadBalancerIP: 192.168.30.151