apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
spec:
  selector:
    app.kubernetes.io/name: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
  loadBalancerIP: 192.168.30.112