apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudflared-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/cloudflared
    type: DirectoryOrCreate