apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: argocd-cloudflared
  name: argocd-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: argocd-cloudflared
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: argocd-cloudflared
    spec:
      containers:
        - env:
            - name: TUNNEL_NAME
              value: argocd-namagomi
            - name: CLOUDFLARED_HOSTNAME
              value: namagomi-argocd.nabr2730.com
            - name: CLOUDFLARED_SERVICE
              value: http://argocd-server.argocd
          image: ghcr.io/namagominetwork/cloudflared-tunnel:2022.6.6-cloudflared22.6.3
          name: argocd-cloudflared
          resources: {}
          volumeMounts:
            - mountPath: /root
              name: cloudflared-pv
      volumes:
        - name: cloudflared-pv
          persistentVolumeClaim:
            claimName: cloudflared-pvc
status: {}