apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: grafana-cloudflared
  name: grafana-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-cloudflared
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: grafana-cloudflared
    spec:
      containers:
        - env:
            - name: TUNNEL_NAME
              value: grafana-namagomi
            - name: CLOUDFLARED_HOSTNAME
              value: grafana.nabr2730.com
            - name: CLOUDFLARED_SERVICE
              value: http://192.168.30.2
          image: ghcr.io/giganticminecraft/cloudflared-with-auto-dns-route:sha-6455b98
          name: grafana-cloudflared
          resources: {}
          volumeMounts:
            - mountPath: /root
              name: cloudflared-home
      volumes:
        - hostPath:
            path: /root
          name: cloudflared-home
status: {}